import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devvara Rishivian
 */
public class dataanggota extends javax.swing.JFrame {
    
    private DefaultTableModel Tabgota;
    Connection Con;
    
    private void LoadData(){
        Object kolom[] = {"NIS","N.SISWA","TTL","Jk","AGAMA","ALAMAT","TGL DAFTAR","BERLAKU HINGGA"};
        Tabgota = new DefaultTableModel(null,kolom);
        Tabta.setModel(Tabgota);
        jScrollPane1.getViewport().add(Tabta,null);
        try{
            Con = null;
            Class.forName("com.mysql.jdbc.Drover");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "" + "SELECT * from anggota";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                String NIS = res.getString("NIS");
                String NamaSiswa = res.getString("NamaSiswa");
                String TTL = res.getString("TempatTglLahir");
                String Kelas = res.getString("Kelas");
                String JenisKelamin = res.getString("JenisKelamin");
                String Alamat = res.getString("Alamat");
                String Agama = res.getString("Agama");
                String TglDaftar = res.getString("TglPendaftaran");
                String Berlaku = res.getString("BerlakuHingga");
                Object[] data = {NIS, NamaSiswa, TTL, Kelas, JenisKelamin, Alamat, Agama, TglDaftar, Berlaku, };
                Tabgota.addRow(data);
            }
            Tabta.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(1).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(2).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(3).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(4).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(5).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(6).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(7).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(8).setPreferredWidth(80);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error : " + ex);
        }
    }
    
    public dataanggota() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Behi = new javax.swing.JTextField();
        NIS = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        TTL = new javax.swing.JTextField();
        Jk = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        Agama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        TD = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Del = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Berlaku Hingga ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 300, 110, 30);

        jLabel2.setText("Data Anggota");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 10, 110, 30);

        jLabel3.setText("NIS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 60, 110, 30);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 90, 110, 30);

        jLabel5.setText("TTL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 120, 110, 30);

        jLabel6.setText("JK");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 150, 110, 30);

        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 180, 110, 30);

        jLabel8.setText("Agama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 110, 30);

        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 240, 110, 30);

        jLabel10.setText("Tgl Daftar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 270, 110, 30);
        getContentPane().add(Behi);
        Behi.setBounds(180, 300, 210, 20);

        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });
        getContentPane().add(NIS);
        NIS.setBounds(180, 60, 210, 20);
        getContentPane().add(Nama);
        Nama.setBounds(180, 90, 210, 20);
        getContentPane().add(TTL);
        TTL.setBounds(180, 120, 210, 20);
        getContentPane().add(Jk);
        Jk.setBounds(180, 150, 210, 20);
        getContentPane().add(Kelas);
        Kelas.setBounds(180, 180, 210, 20);
        getContentPane().add(Agama);
        Agama.setBounds(180, 210, 210, 20);
        getContentPane().add(Alamat);
        Alamat.setBounds(180, 240, 210, 20);
        getContentPane().add(TD);
        TD.setBounds(180, 270, 210, 20);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(400, 130, 80, 30);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh);
        Refresh.setBounds(500, 70, 80, 30);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(400, 190, 80, 30);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(400, 70, 80, 30);

        Del.setText("Delete");
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });
        getContentPane().add(Del);
        Del.setBounds(500, 130, 80, 30);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(500, 190, 80, 30);

        Tabta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama", "TTL", "JK", "Kelas", "Agama", "Alamat", "TGL Daftar", "Berlaku Hingga"
            }
        ));
        jScrollPane1.setViewportView(Tabta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 370, 610, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sqlnya = ("insert into anggota values ('"+NIS.getText()+"','"+Nama.getText()+"','"+TTL.getText()+"','"+
                Jk.getText()+"','"+Alamat.getText()+"','"+Agama.getText()+"','"+TD.getText()+"','"+Behi.getText()+"','"+Kelas.getText()+"')");
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            LoadData();
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_SaveActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        NIS.setText(null);
        Nama.setText(null);
        TTL.setText(null);
        Jk.setText(null);
        Alamat.setText(null);
        Agama.setText(null);
        TD.setText(null);
        Behi.setText(null);
        Kelas.setText(null);
    }//GEN-LAST:event_RefreshActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:

        int coba = JOptionPane.showConfirmDialog(null, "Yakin Record?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "update anggota set NIS=?, NamaSiswa?, JenisKelamin=?, TempatTglLahir=?, Agama=?, TglPendaftaran=?,"
                    + "BerlakuHingga=?, Kelas=? where NIS='"+NIS.getText()+"'";
            PreparedStatement st = connection.prepareStatement(sql);
            if(coba==0){
                try{
                    st.setString(1, NIS.getText());
                    st.setString(2, Nama.getText());
                    st.setString(3, TTL.getText());
                    st.setString(4, Jk.getText());
                    st.setString(5, Alamat.getText());
                    st.setString(6, Agama.getText());
                    st.setString(7, TD.getText());
                    st.setString(8, Behi.getText());
                    st.setString(9, Kelas.getText());
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_EditActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null, "Masukkan NIS !!!");

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM anggota WHERE NIS='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                LoadData();
                NIS.setText(rsnya.getString(1));
                Nama.setText(rsnya.getString(2));
                TTL.setText(rsnya.getString(3));
                Jk.setText(rsnya.getString(4));
                Alamat.setText(rsnya.getString(5));
                Agama.setText(rsnya.getString(6));
                TD.setText(rsnya.getString(7));
                Behi.setText(rsnya.getString(8));
                Kelas.setText(rsnya.getString(9));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        // TODO add your handling code here:

        String x = NIS.getText();
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sql = "DELETE FROM anggota WHERE NIS='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
            LoadData();
            NIS.setText(null);
            Nama.setText(null);
            TTL.setText(null);
            Alamat.setText(null);
            Agama.setText(null);
            TD.setText(null);
            Behi.setText(null);
            Kelas.setText(null);
            
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_DelActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(null, "Yakin?","Yakin", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION){
        this.dispose();
         new ADMIN().show();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISActionPerformed
        // TODO add your handling code here:
        String x = NIS.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM databuku WHERE anggota='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                LoadData();
                NIS.setText(rsnya.getString(1));
                Nama.setText(rsnya.getString(2));
                TTL.setText(rsnya.getString(3));
                Jk.setText(rsnya.getString(4));
                Alamat.setText(rsnya.getString(5));
                Agama.setText(rsnya.getString(6));
                TD.setText(rsnya.getString(7));
                Behi.setText(rsnya.getString(8));
                Kelas.setText(rsnya.getString(9));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
    }//GEN-LAST:event_NISActionPerformed
    }
    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataanggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agama;
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Behi;
    private javax.swing.JButton Del;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Jk;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JTextField TD;
    private javax.swing.JTextField TTL;
    private javax.swing.JTable Tabta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
