import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devvara Rishivian
 */
public class dataanggota extends javax.swing.JFrame {
    
    private DefaultTableModel Tabgota;
    Connection Con;
    
    private void LoadData(){
        Object kolom[] = {"NIS","N.SISWA","TTL","Jk","AGAMA","ALAMAT","TGL DAFTAR","BERLAKU HINGGA"};
        Tabgota = new DefaultTableModel(null,kolom);
        Tabta.setModel(Tabgota);
        jScrollPanel.getViewport().add(Tabta,null);
        try{
            Con = null;
            Class.forName("com.mysql.jdbc.Drover");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "" + "SELECT * from anggota";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                String NIS = res.getString("NIS");
                String NamaSiswa = res.getString("NamaSiswa");
                String TTL = res.getString("TempatTglLahir");
                String Kelas = res.getString("Kelas");
                String JenisKelamin = res.getString("JenisKelamin");
                String Alamat = res.getString("Alamat");
                String Agama = res.getString("Agama");
                String TglDaftar = res.getString("TglPendaftaran");
                String Berlaku = res.getString("BerlakuHingga");
                Object[] data = {NIS, NamaSiswa, TTL, Kelas, JenisKelamin, Alamat, Agama, TglDaftar, Berlaku, };
                Tabgota.addRow(data);
            }
            Tabta.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(1).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(2).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(3).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(4).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(5).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(6).setPreferredWidth(50);
            Tabta.getColumnModel().getColumn(7).setPreferredWidth(80);
            Tabta.getColumnModel().getColumn(8).setPreferredWidth(80);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error : " + ex);
        }
    }
    
    public dataanggota() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Berlaku sampai ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 300, 110, 30);

        jLabel2.setText("Data Anggota");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 10, 110, 30);

        jLabel3.setText("NIS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 60, 110, 30);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 90, 110, 30);

        jLabel5.setText("TTL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 120, 110, 30);

        jLabel6.setText("JK");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 150, 110, 30);

        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 180, 110, 30);

        jLabel8.setText("Agama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 110, 30);

        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 240, 110, 30);

        jLabel10.setText("Tgl Daftar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 270, 110, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 300, 210, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 60, 210, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 90, 210, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 120, 210, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 150, 210, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 180, 210, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 210, 210, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 240, 210, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 270, 210, 20);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 190, 80, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 70, 80, 30);

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 130, 80, 30);

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 70, 80, 30);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 130, 80, 30);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(500, 190, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama", "TTL", "JK", "Kelas", "Agama", "Alamat", "TGL Daftar", "Berlaku Hingga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 370, 610, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sqlnya = ("insert into databuku values ('"+Kode.getText()+"','"+Nama.getText()+"','"+Nampeng.getText()+"','"+
                bit.getText()+"','"+tahun.getText()+"')");
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            LoadData();
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Kode.setText(null);
        Nama.setText(null);
        Nampeng.setText(null);
        bit.setText(null);
        tahun.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int coba = JOptionPane.showConfirmDialog(null, "Yakin Ubah Data?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "update databuku set KodeBuku=?, NamaBuku?, NamaPengarang=?, Penerbit=?, TahunTerbit=? where "+
            "KodeBuku='"+Kode.getText()+"'";
            PreparedStatement st = connection.prepareStatement(sql);
            if(coba == 0){
                try{
                    st.setString(1, Kode.getText());
                    st.setString(2, Nama.getText());
                    st.setString(3, Nampeng.getText());
                    st.setString(4, bit.getText());
                    st.setString(5, tahun.getText());
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal"+e);
                }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null, "Masukkan Kode Buku !!!");

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM databuku WHERE KodeBuku='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                LoadData();
                Kode.setText(rsnya.getString(1));
                Nama.setText(rsnya.getString(2));
                Nampeng.setText(rsnya.getString(3));
                bit.setText(rsnya.getString(4));
                tahun.setText(rsnya.getString(5));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String x = Kode.getText();
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sql = "DELETE FROM databuku WHERE KodeBuku='"+x+"'";
            stat.executeUpdate(sql);
            JOPtionPane.showMessageDialog(null, "Data Telah Dihapus");
            LoadData();
            Kode.setText(null);
            Nama.setText(null);
            Nampeng.setText(null);
            bit.setText(null);
            tahun.setText(null);
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(null, "Yakin?","Yakin", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION){
            new ADMIN().show();
            this.dispose();}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        String x = NIS.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM databuku WHERE anggota='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                LoadData();
                NIS.setText(rsnya.getString(1));
                Nama.setText(rsnya.getString(2));
                TTL.setText(rsnya.getString(3));
                Jk.setText(rsnya.getString(4));
                Alamat.setText(rsnya.getString(5));
                Agama.setText(rsnya.getString(6));
                TD.setText(rsnya.getString(7));
                Behi.setText(rsnya.getString(8));
                Kelas.setText(rsnya.getString(9));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataanggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataanggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
