
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dafa Zakhulhaq
 */
public class databuku extends javax.swing.JFrame {
    
    private DefaultTableModel Tabbuk;
    Connection Con;
    
    private void LoadData(){
        
        Object kolom[] = {"KODE BUKU","NAMA BUKU","NAMA PENGARANG","PENERBIT","TAHUN TERBIT"};
        Tabbuk = new DefaultTableModel(null,kolom);
        Tabuk.setModel(Tabbuk);
        jScrollPane1.getViewport().add(Tabuk,null);
        try{
            Con = null;
            Class.forName("com.mysql.jbdc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan", "root", "");
            String sql = "" + "SELECT * from databuku";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                String KodeBuku = res.getString("KodeBuku");
                String NamaBuku = res.getString("NamaBuku");
                String NamaPengarang = res.getString("NamaPengarang");
                String Penerbit = res.getString("Penerbit");    
                String TahunTerbit = res.getString("TahunTerbit");
                Object[] data = {KodeBuku, NamaBuku, NamaPengarang, Penerbit, TahunTerbit, };
                Tabbuk.addRow(data);                
            }
            Tabuk.getColumnModel().getColumn(0).setPreferredWidth(20);
            Tabuk.getColumnModel().getColumn(1).setPreferredWidth(100);
            Tabuk.getColumnModel().getColumn(2).setPreferredWidth(100);
            Tabuk.getColumnModel().getColumn(3).setPreferredWidth(20);
            Tabuk.getColumnModel().getColumn(4).setPreferredWidth(80);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error : " + ex);
        }
    }

    
    public databuku() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        Kode = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Nampeng = new javax.swing.JTextField();
        bit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabuk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama Buku");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 60, 30);

        jLabel2.setText("DATA BUKU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 0, 80, 40);

        jLabel3.setText("Kode Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 80, 40);

        jLabel4.setText("Nama Pengarang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 110, 40);

        jLabel5.setText("Tahun Terbit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 90, 30);

        jLabel6.setText("Penertbit");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 150, 60, 30);
        getContentPane().add(tahun);
        tahun.setBounds(140, 180, 120, 30);
        getContentPane().add(Kode);
        Kode.setBounds(140, 60, 120, 30);
        getContentPane().add(Nama);
        Nama.setBounds(140, 90, 120, 30);
        getContentPane().add(Nampeng);
        Nampeng.setBounds(140, 120, 120, 30);
        getContentPane().add(bit);
        bit.setBounds(140, 150, 120, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 180, 80, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 60, 80, 30);

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 120, 80, 30);

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 60, 80, 30);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 120, 80, 30);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(370, 180, 80, 30);

        Tabuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabuk);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 452, 120);

        setBounds(0, 0, 479, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Kode.setText(null);
        Nama.setText(null);
        Nampeng.setText(null);
        bit.setText(null);
        tahun.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 // TODO add your handling code here:
 
 if(JOptionPane.showConfirmDialog(null, "Yakin Keluar?","Yakin",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
     this.dispose();
     new ADMIN().show();
 }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null, "Masukkan Kode Buku !!!");
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM databuku WHERE KodeBuku='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            if(rsnya.next()){
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                LoadData();
                Kode.setText(rsnya.getString(1));
                Nama.setText(rsnya.getString(2));
                Nampeng.setText(rsnya.getString(3));
                bit.setText(rsnya.getString(4));
                tahun.setText(rsnya.getString(5));
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sqlnya = ("insert into databuku values ('"+Kode.getText()+"','"+Nama.getText()+"','"+Nampeng.getText()+"','"+
                    bit.getText()+"','"+tahun.getText()+"')");
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            LoadData();
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int coba = JOptionPane.showConfirmDialog(null, "Yakin Ubah Data?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "update databuku set KodeBuku=?, NamaBuku?, NamaPengarang=?, Penerbit=?, TahunTerbit=? where "+
                    "KodeBuku='"+Kode.getText()+"'";
            PreparedStatement st = connection.prepareStatement(sql);
            if(coba == 0){
                try{
                    st.setString(1, Kode.getText());
                    st.setString(2, Nama.getText());
                    st.setString(3, Nampeng.getText());
                    st.setString(4, bit.getText());
                    st.setString(5, tahun.getText());
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    LoadData();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Update Data Gagal"+e);
                }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String x = Kode.getText();
        try{
            Class.forName("com.mysql.jdbc.Drive");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sql = "DELETE FROM databuku WHERE KodeBuku='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
            LoadData();          
        Kode.setText(null);
        Nama.setText(null);
        Nampeng.setText(null);
        bit.setText(null);
        tahun.setText(null);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi Gagal"+e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kode;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nampeng;
    private javax.swing.JTable Tabuk;
    private javax.swing.JTextField bit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables
}
