import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.rmi.transport.Transport;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author W8
 */
public class Karyawan extends javax.swing.JFrame {

   int Gajian;
   int Transpot=70000;
   
   private DefaultTableModel Tabkarya;
   Connection Con;
   
   private void LoadData() throws ClassNotFoundException, SQLException{
   Object kolom[] = {"NIK", "NAKAR", "JK", "GOL","JAB", "ABSEN", "JA", "B.TRANSPOT","TUNJANG", "GAJI"};
   Tabkarya = new DefaultTableModel(null,kolom);
   Tabkar.setModel(Tabkarya);
   jScrollPane1.getViewport().add(Tabkar,null);
   try{
   Con = null;
   Class.forName("com.mysql.jbdc.Driver");
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
   String sql = "" + "SELECT * from karyawan";
   Statement stat = con.createStatement();
   ResultSet res = stat.executeQuery(sql);
   while(res.next()) {
   String NIK = res.getString("NIK");
   String NamaKaryawan = res.getString("NamaKaryawan");
          String JenisKelamin = res.getString("JenisKelamin");
          String Golongan = res.getString("Golongan");
          String Jabatan = res.getString("Jabatan");
          String Absen = res.getString("Absen");
          String JumlahAbsen = res.getString("JumlahAbsen");
          String BiayaTransport = res.getString("BiayaTransport");
          String Tunjangan = res.getString("Tunjangan");
          String Gaji = res.getString("Gaji");
   Object[] data = {NIK, NamaKaryawan, JenisKelamin, Golongan, Jabatan, Absen, JumlahAbsen, BiayaTransport, Tunjangan, Gaji};
          Tabkarya.addRow(data);
   }
   Tabkar.getColumnModel().getColumn(0).setPreferredWidth(50);
   Tabkar.getColumnModel().getColumn(1).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(2).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(3).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(4).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(5).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(6).setPreferredWidth(50);
   Tabkar.getColumnModel().getColumn(7).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(8).setPreferredWidth(80);
   Tabkar.getColumnModel().getColumn(9).setPreferredWidth(80);
   } catch (Exception ex) {
       JOptionPane.showMessageDialog(this,"Error : "+ex);
   
   } }
  
    public Karyawan() {
        initComponents();
        setLocationRelativeTo(null);
        Load();
    }
    
    private void Load(){
        NIK.setText(null);
        Nakar.setText(null);
        Jk.setText(null);
        Gol.setText(null);
        Jab.setText(null);
        Ab.setText("0");
        Ja.setText("0");
        Bt.setText("0");
        Tun.setText("0");
        Gaji.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Gaji = new javax.swing.JTextField();
        NIK = new javax.swing.JTextField();
        Nakar = new javax.swing.JTextField();
        Jk = new javax.swing.JTextField();
        Gol = new javax.swing.JTextField();
        Jab = new javax.swing.JTextField();
        Ab = new javax.swing.JTextField();
        Ja = new javax.swing.JTextField();
        Bt = new javax.swing.JTextField();
        Tun = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabkar = new javax.swing.JTable();
        Save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        Save1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Edit2 = new javax.swing.JButton();
        Save2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel1.setText("Data Karyawan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(152, 11, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah Gaji");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 330, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NIK");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 60, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama Karyawan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 90, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 120, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Golongan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 150, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jabatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 180, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Absen");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 210, 60, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jumlah Absen");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 240, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Biaya Transport");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 270, 120, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tunjangan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 300, 110, 17);
        getContentPane().add(Gaji);
        Gaji.setBounds(190, 330, 150, 20);
        getContentPane().add(NIK);
        NIK.setBounds(190, 60, 150, 20);
        getContentPane().add(Nakar);
        Nakar.setBounds(190, 90, 150, 20);
        getContentPane().add(Jk);
        Jk.setBounds(190, 120, 150, 20);

        Gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolActionPerformed(evt);
            }
        });
        getContentPane().add(Gol);
        Gol.setBounds(190, 150, 150, 20);
        getContentPane().add(Jab);
        Jab.setBounds(190, 180, 150, 20);

        Ab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbActionPerformed(evt);
            }
        });
        getContentPane().add(Ab);
        Ab.setBounds(190, 210, 150, 20);
        getContentPane().add(Ja);
        Ja.setBounds(190, 240, 150, 20);
        getContentPane().add(Bt);
        Bt.setBounds(190, 270, 150, 20);
        getContentPane().add(Tun);
        Tun.setBounds(190, 300, 150, 20);

        Tabkar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Jenis Kelamin", "Golongan", "Jabatan", "Absen", "Jumlah Absen", "Biaya Transport", "Tunjangan", "Jumlah gaji"
            }
        ));
        jScrollPane1.setViewportView(Tabkar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 370, 670, 180);

        Save.setText("Hitung");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(460, 220, 90, 40);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 70, 90, 40);

        Edit1.setText("Edit");
        getContentPane().add(Edit1);
        Edit1.setBounds(390, 120, 90, 40);

        Save1.setText("Exit");
        getContentPane().add(Save1);
        Save1.setBounds(530, 170, 90, 40);

        jButton3.setText("Refresh");
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 70, 90, 40);

        Edit2.setText("Delete");
        getContentPane().add(Edit2);
        Edit2.setBounds(530, 120, 90, 40);

        Save2.setText("Save");
        getContentPane().add(Save2);
        Save2.setBounds(390, 170, 90, 40);

        setBounds(0, 0, 683, 604);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String x= JOptionPane.showInputDialog(null, "Masukan NIK!!");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriveManager.getConnection("jdbc:mysql://localhost:/perpustakaan","root","");
            Statment stat=connection.createStatement();
            String cari="SELECT * FROM karyawan WHERE NIK='"+x+"'";
            ResultSet rsnya= stat.executeQuery(cari);
            JOptionPane.showMessageDialog(null, "Data Ditemukan");
            LoadData();
            if (rsnya.next()){
            System.out.print(rsnya.getString(1));
            NIK.setText(rsnya.getString(1));
            Nakar.setText(rsnya.getString(2));
            Jk.setText(rsnya.getString(3));
            Gol.setText(rsnya.getString(4));
            Jab.setText(rsnya.getString(5));
            Ab.setText(rsnya.getString(6));
            Ja.setText(rsnya.getString(7));
            Bt.setText(rsnya.getString(8));
            Tun.setText(rsnya.getString(9));
            Gaji.setText(rsnya.getString(10));
            
            
        }else{
              JOptionPane.showMassageDialog(null, "Data tidak ada");
            }
        }catch(Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolActionPerformed
        // TODO add your handling code here:
        int golongan=Integer.parseInt(Gol.getText());
        switch (golongan){
            case 1:
                Jab.setText("Manager");
                Tun.setText("700000");
                break;
            case 2:
                Jab.setText("Supervisor");
                Tun.setText("500000");
                break;
            case 3:
                Jab.setText("Staff");
                Tun.setText("300000");
                break;
            case 4:
                Jab.setText("ass staf");
                Tun.setText("250000");
                break;
            case 5:
                Jab.setText("Honorer");
                Tun.setText("200000");
                break;
            default:
                JOpitonPane.showMessageDialog(null, "Maaf anda salah input , silahkan pilih 1 sampai 5");
                Jab.setText("");
                Gaji.setText("");
        }
    }//GEN-LAST:event_GolActionPerformed

    private void AbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(Ab.getText());
        int x=a+Integer.parseInt(Ja.getText());
        Ja.setText(""+x);
        
        int c=Integer.parseInt(Bt.getText());
        int y=x*Transport;
        Bt.setText(""+y);
    }//GEN-LAST:event_AbActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        int Golongan=Integer.parseInt(Gol.getText());
        int Btrans=Integer.parseInt(Bt.getText());
        int Tunjangan=Integer.parseInt(Tun.getText());
        int Y=Btrans+Tunjangan+Gajian;
        
        if(Golongan==1){
            Gajian=2000000;
            Gaji.setText(""+Y);
        }else if(Golongan==2){
            Gajian=1500000;
            Gaji.setText(""+Y);
        }else if(Golongan==3){
            Gajian=1000000;
            Gaji.setText(""+Y);
        }else if(Golongan==4){
            Gajian=750000;
            Gaji.setText(""+Y);
        }else if(Golongan==5){
            Gajian=500000;
            Gaji.setText(""+Y);
        }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ab;
    private javax.swing.JTextField Bt;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JTextField Gaji;
    private javax.swing.JTextField Gol;
    private javax.swing.JTextField Ja;
    private javax.swing.JTextField Jab;
    private javax.swing.JTextField Jk;
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField Nakar;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JButton Save2;
    private javax.swing.JTable Tabkar;
    private javax.swing.JTextField Tun;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static class JOpitonPane {

        public JOpitonPane() {
        }
    }
}
