/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fariz
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class Pinjam extends javax.swing.JFrame {

    private DefaultTableModel Tabpin;
    Connection Con;
    
    private void LoadData() {
        Object kolom[] = {"NIS","N. SISWA","K. BUKU","N. BUKU", "PENERBIT", "TGL PINJAM", "TGL KEMBALI", "LAMA PINJAM"};
        Tabpin = new DefaultTableModel(null, kolom);
        jTable4.setModel(Tabpin);
        jScrollPane2.getViewport().add(jTable4,null);
        
        try{
            Con = null;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            String sql = "" + "SELECT * from peminjam";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                String NIS = res.getString("NIS");
                String NamaSiswa = res.getString("NamaSiswa");
                String Kelas = res.getString("Kelas");
                String KodeBuku = res.getString("KodeBuku");
                String NamaBuku = res.getString("NamaBuku");
                String Penerbit = res.getString("Penerbit");
                String TglPinjam = res.getString("TglPinjam");
                String TglKembali = res.getString("TglKembali");
                String LamaPinjam = res.getString("LamaPinjam");
                Object[] data = {NIS,NamaSiswa,Kelas,KodeBuku,NamaBuku,Penerbit,TglPinjam,TglKembali,LamaPinjam};
                //Object[] data = [NIS,NamaSiswa,Kelas,KodeBuku,NamaBuku,Penerbit,TglPinjam,TglKembali,LamaPinjam];
                Tabpin.addRow(data);
            }
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(6).setPreferredWidth(80);
            jTable4.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable4.getColumnModel().getColumn(8).setPreferredWidth(50);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,""+e);
        }
    }
    
    /**
     * Creates new form datapeminjam
     */
    public Pinjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nasis = new javax.swing.JTextField();
        Kel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        KB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nabuk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TglPin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TglKem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Lampin = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA PEMINJAM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 270, 50);

        jLabel2.setText("NIS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 160, 30);

        KS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KSActionPerformed(evt);
            }
        });
        getContentPane().add(KS);
        KS.setBounds(190, 70, 200, 30);

        jLabel3.setText("Nama Siswa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 160, 30);

        Nasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NasisActionPerformed(evt);
            }
        });
        getContentPane().add(Nasis);
        Nasis.setBounds(190, 110, 200, 30);

        Kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelActionPerformed(evt);
            }
        });
        getContentPane().add(Kel);
        Kel.setBounds(190, 150, 200, 30);

        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 160, 30);

        KB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBActionPerformed(evt);
            }
        });
        getContentPane().add(KB);
        KB.setBounds(190, 190, 200, 30);

        jLabel5.setText("Kode Buku");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 160, 30);

        Nabuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NabukActionPerformed(evt);
            }
        });
        getContentPane().add(Nabuk);
        Nabuk.setBounds(190, 230, 200, 30);

        jLabel6.setText("Nama Buku");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 160, 30);

        jLabel7.setText("Penerbit");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 270, 160, 30);

        Pen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenActionPerformed(evt);
            }
        });
        getContentPane().add(Pen);
        Pen.setBounds(190, 270, 200, 30);

        jLabel8.setText("Tgl Pinjam");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 160, 30);

        TglPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglPinActionPerformed(evt);
            }
        });
        getContentPane().add(TglPin);
        TglPin.setBounds(190, 310, 200, 30);

        jLabel9.setText("Tgl Kembali");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 350, 160, 30);

        TglKem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglKemActionPerformed(evt);
            }
        });
        getContentPane().add(TglKem);
        TglKem.setBounds(190, 350, 200, 30);

        jLabel10.setText("Lama Pinjam");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 390, 160, 30);

        Lampin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LampinActionPerformed(evt);
            }
        });
        getContentPane().add(Lampin);
        Lampin.setBounds(190, 390, 200, 30);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA SISWA", "KELAS", "KODE BUKU", "NAMA BUKU", "PENERBIT", "TGL PINJAM", "TGL KEMBALI", "LAMA PINJAM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 430, 600, 120);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 70, 80, 50);

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 140, 80, 50);

        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(410, 210, 80, 50);

        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(520, 70, 80, 50);

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(520, 140, 80, 50);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 210, 80, 50);

        setBounds(0, 0, 641, 599);
    }// </editor-fold>//GEN-END:initComponents

    private void KSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KSActionPerformed
        // TODO add your handling code here:
        String x = KS.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan", "root", "") ;
           // Connection connection = Drivermanager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String cari = "SELECT * FROM peminjam WHERE NIS='"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            
            if(rsnya.next()) {
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(rootPane, "Data ditemukan");
                LoadData();
                KS.setText(rsnya.getString(1));
                Nasis.setText(rsnya.getString(2));
                Kel.setText(rsnya.getString(3));
                KB.setText(rsnya.getString(4));
                Nabuk.setText(rsnya.getString(5));
                Pen.setText(rsnya.getString(6));
                TglPin.setText(rsnya.getString(7));
                TglKem.setText(rsnya.getString(8));
                Lampin.setText(rsnya.getString(9));
                }
            else {
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi gagal");
        }
    }//GEN-LAST:event_KSActionPerformed

    private void NasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NasisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NasisActionPerformed

    private void KelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelActionPerformed

    private void KBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KBActionPerformed

    private void NabukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NabukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NabukActionPerformed

    private void PenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenActionPerformed

    private void TglPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TglPinActionPerformed

    private void TglKemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglKemActionPerformed
        // TODO add your handling code here:
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            java.util.Date TanggalCEKIN = df.parse(TglPin.getText());
            java.util.Date TanggalCEKOUT = df.parse(TglKem.getText());
            
            long Hari1 = TanggalCEKIN.getTime();
            long Hari2 = TanggalCEKOUT.getTime();
            long diff = Hari2 - Hari1;
            long lama = diff / (24 * 60 * 60 * 1000);
            Lampin.setText(Long.toString(lama));
            }
        catch (ParseException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TglKemActionPerformed

    private void LampinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LampinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LampinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null, "Masukkan NIS!");
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan", "root", "") ;
            Statement stat=connection.createStatement();
            String cari = "SELECT * FROM peminjam WHERE NIS = '"+x+"'";
            ResultSet rsnya = stat.executeQuery(cari);
            
            if(rsnya.next()) {
                System.out.print(rsnya.getString(1));
                JOptionPane.showMessageDialog(rootPane, "Data ditemukan");
                LoadData();
                KS.setText(rsnya.getString(1));
                Nasis.setText(rsnya.getString(2));
                Kel.setText(rsnya.getString(3));
                KB.setText(rsnya.getString(4));
                Nabuk.setText(rsnya.getString(5));
                Pen.setText(rsnya.getString(6));
                TglPin.setText(rsnya.getString(7));
                TglKem.setText(rsnya.getString(8));
                Lampin.setText(rsnya.getString(9));
                
            } 
            else {
                JOptionPane.showMessageDialog(null, "Data tidak ada");
            }
             }
            catch (Exception e) {
                    System.out.print(e);
                    JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int coba = JOptionPane.showConfirmDialog(null, "Yakin untuk mengubah data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan", "root", "") ;
            Statement stat=connection.createStatement();
            String sql = "update peminjam set NIS=?, NamaSiswa=?, Kelas=?, KodeBuku=?, NamaBuku=?, Penerbit=?,"+"TglPinjam=?,TglKembali=?,LamaPinjam=? where" + "NIS='" + KS.getText()+"'";
            PreparedStatement st = connection.prepareStatement(sql);
            if(coba==0) {
                try{
                    st.setString(1,KS.getText());
                    st.setString(2,Nasis.getText());
                    st.setString(3,Kel.getText());
                    st.setString(4,KB.getText());
                    st.setString(5,Nabuk.getText());
                    st.setString(6,Pen.getText());
                    st.setString(7,TglPin.getText());
                    st.setString(8,TglKem.getText());
                    st.setString(9,Lampin.getText());
                    st.executeUpdate();
                    LoadData();
                }
                catch (Exception e){
                    
                    JOptionPane.showMessageDialog(null, "Update Data Sukses");
                    
                }
            }
        }
             catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
             }
           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sqlnya = ("insert into peminjam values ('"+KS.getText()+"','"+Nasis.getText()+"','"+Kel.getText()+"','"+
                    KB.getText()+"','"+Nabuk.getText()+"','"+Pen.getText()+"','"+TglPin.getText()+"','"+TglKem.getText()+"','"+Lampin.getText()+"')");
            
            PreparedStatement p=connection.prepareStatement(sqlnya) ;
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            LoadData();
        }catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

            KS.setText(null);
        Nasis.setText(null);
        Kel.setText(null);
        KB.setText(null);
        Nabuk.setText(null);
        Pen.setText(null);
        TglPin.setText(null);
        TglKem.setText(null);
        Lampin.setText(null);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

String x = KS.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan", "root", "");
            Statement stat = connection.createStatement();
            String sql = "DELETE FROM peminjam WHERE NIS = '"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
            KS.setText("");
            Nasis.setText("");
            Kel.setText("");
            KB.setText("");
            Nabuk.setText("");
            Pen.setText("");
            TglPin.setText("");  
            TglKem.setText("");
            Lampin.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi gagal");
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


        this.dispose();
        new Loginadmin().setVisible(true) ;
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KB;
    private javax.swing.JTextField KS;
    private javax.swing.JTextField Kel;
    private javax.swing.JTextField Lampin;
    private javax.swing.JTextField Nabuk;
    private javax.swing.JTextField Nasis;
    private javax.swing.JTextField Pen;
    private javax.swing.JTextField TglKem;
    private javax.swing.JTextField TglPin;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
